GET http://localhost:8000/mascotas/buscarMascota HTTP/1.1

###
GET http://localhost:8000/mascotas/buscarGatos HTTP/1.1


###
GET http://localhost:8000/mascotas/buscarperros HTTP/1.1

###
GET http://localhost:8000/mascotas/buscarMascotasDiponibles HTTP/1.1

###
POST http://localhost:8000/mascotas/crearMascota HTTP/1.1
Content-Type: application/json

{
    "id_mascota": 121,
    "nombre": "Mateo",
    "tipo": "gato",
    "edad": 3,
    "descripcion": "Un perro jugueton",
    "disponible": false
}

###
GET http://localhost:8000/mascotas/buscarMascota/125 HTTP/1.1

###
PUT http://localhost:8000/mascotas/actualizarMascota/166 HTTP/1.1
Content-Type: application/json

{
    "nombre":"Max",
    "edad":10
}

###
DELETE http://localhost:8000/mascotas/eliminarMascota/123 HTTP/1.1



###
POST http://localhost:8000/solicitudes/crearSolicitud HTTP/1.1
Content-Type: application/json

{
    "id_Solicitud": 124,
    "idMascota": 1,
    "nombreSolicitante": "Fredy",
    "correoSolicitante": "FREDY@gmail.com"
}


###
GET http://localhost:8000/solicitudes/buscarIdSolicitud/11 HTTP/1.1


###
GET http://localhost:8000/solicitudes/buscarSolicitudes HTTP/1.1

###
PUT http://localhost:8000/solicitudes/actualizarSolicitud/12 HTTP/1.1
Content-Type: application/json

{
    "nombreSolicitante": "Daniel Getial",
    "correoSolicitante": "FREDY@gmail.com",
    "estadoSolicitud": "aceptada"
}

###
DELETE http://localhost:8000/solicitudes/eliminarSolicitud/11 HTTP/1.1